name: tumor-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - fenics
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - jupyterlab
  - tqdm
  - pip
  - pip:
    - torch
    - torchvision
    - hippylib
    - pytorch-minimize